apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-end-ingress
  namespace: sock-shop
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: front-end
          servicePort: 80