---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  annotations:
    kubernetes.io/role/elb: "1"
    kubernetes.io/ingress.class: alb
  labels:
    name: front-end
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  - port: 443
    targetPort: 8079
    nodePort: 30002
    protocol: TCP
    name: https
  selector:
    name: front-end
