---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    name: front-end
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: front-end
